package ca.adamhammer.shimmer.model

import kotlinx.serialization.Serializable

/**
 * Standardized result model for image generation operations.
 *
 * @param base64 The generated image encoded as a Base64 string.
 * @param prompt The original prompt used to generate the image.
 * @param revisedPrompt The revised prompt generated by the AI (if applicable).
 */
@Serializable
data class ImageResult(
    val base64: String = "",
    val prompt: String = "",
    val revisedPrompt: String = ""
)
